### PR TITLE
Add option to use renewable periodic token

### PR DESCRIPTION
**Pull request by gobins**
Vault tokens expire by default after the max_ttl set on the token backend. 
The currently implementation of secrets api does not cater for use of renewable periodic tokens. 
This change implements token renewal.

### CODE REVIEW

**Comment by cloudnautique** [comment]
Thanks for contributing this. This is a feature that was missing for sure. 

I would prefer a different path for the initialization though. Instead of exporting `GetVaultClient` out backends, I would rather it be done in `config.SetBackendConfigs()` workflow. It would allow early error detection that isn't there right now. A user can't find out vault is misconfigured until they create the first secret.

Then the flow would be, if there is a Vault token in the config then create a client, and start managing the renewals at that point. I would add a package level variable that has the client that is initialized in NewClient. Subsequent calls to vault.NewClient() could check if the package var is set, if it is return the package client, if not initialize and return a new client. 

Also, if I recall there is a way to test if a token is renewable. If a non-renewable token is passed in, then we can just bypass the renewer stuff. If a renewable token is passed in, and can't be renewed then I think we need to fail harder and log errors. 

Just as a heads up on this, there is a refactor going on. We are in the process of adding a dynamic backend for Vault that will mimic our secrets-bridge catalog item. Essentially it will create tokens based on policy so that containers could then talk to vault directly.

**Comment by gobins** [comment]
Please hold on the review, let me get it all touched up. Just trying to figure out working with rancher/trash.

**Comment by gobins** [comment]
Hi @cloudnautique, sorry this took a while to get done. Not sure if the changes are still relevant with regards to your refactoring work.

Here is a list of changes from your last review:

1.  Checks for renewable token have been added. If the token is non renewable , there will be an error in the logs at startup.
2. Initialization of vault client has been moved to config.SetBackendConfigs
3. Package level variable added for vault.Client
4. Integration tests has been updated to use periodic token generated from token role.

Let me know if the changes looks alright to you. We are looking forward to using this feature with our Rancher instance.

**Comment by cjellick** [comment]
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

**Pull request closed without merging**
